DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
 ID INT PRIMARY KEY,
 EMAIL VARCHAR(20),
 LANDLINE_NO VARCHAR(10),
 MOBILE_NO VARCHAR(10) NOT NULL
);

INSERT INTO CONTACT (ID,EMAIL,LANDLINE_NO,MOBILE_NO) VALUES
(1,'test1@abc.com','080123454','98865301'),
(2,'test2@abc.com',null,'98865302'), 
(3,'test3@abc.com','080123456','98865303');

DROP TABLE IF EXISTS CUSTOMER;
 
CREATE TABLE CUSTOMER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  MIDDLE_NAME VARCHAR(250) NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  DOB DATE NOT NULL,
  DOR DATE NOT NULL,
  TYPE VARCHAR(6) NOT NULL,
  HOUSE_NO VARCHAR2(3) NULL,
  STREET VARCHAR2(30) NULL,
  LANDMARK VARCHAR2(100) NULL,
  CITY VARCHAR2(10) NOT NULL,
  STATE VARCHAR2(10) NOT NULL,
  COUNTRY VARCHAR2(10) NOT NULL,
  PINCODE VARCHAR2(6) NOT NULL,
  REMARK VARCHAR(250) NULL  
);

INSERT INTO CUSTOMER 
  (FIRST_NAME,MIDDLE_NAME,LAST_NAME,DOB,DOR,TYPE,HOUSE_NO,STREET,LANDMARK,CITY,STATE,COUNTRY,PINCODE,REMARK) VALUES
  ('test1', null, 'user1','1980-01-01',CURRENT_DATE,'TRADER',null,null,null,'Mumbai','MH','India','123456','comment1'),
  ('test2', 'jk', 'user2','1990-01-01',CURRENT_DATE,'FARMER',null,'church street',null,'Mumbai','MH','India','123456',null),
  ('test3', null, 'user3','1990-01-01',CURRENT_DATE,'TRADER',10/1,'temple street',null,'Mumbai','MH','India','123456','comment3');
