INSERT INTO  USER_INFO (ID,USER_NAME, PASSWORD, ROLES, ENABLED) VALUES (1,'user','user123','ROLE_USER',true);
INSERT INTO  USER_INFO (ID,USER_NAME, PASSWORD, ROLES, ENABLED) VALUES (2,'admin','admin123','ROLE_ADMIN',true);

INSERT INTO  COMMODITY_INFO (ID,NAME,STORAGE_CHARGE,TYPE,UNIT_PRICE) VALUES (1,'Wheat',3.50,'GRAIN',1400);
INSERT INTO  COMMODITY_INFO (ID,NAME,STORAGE_CHARGE,TYPE,UNIT_PRICE) VALUES (2,'Corn',2.50,'GRAIN',1000);
INSERT INTO  COMMODITY_INFO (ID,NAME,STORAGE_CHARGE,TYPE,UNIT_PRICE) VALUES (3,'Soyabean',3.50,'OILY',1400);