INSERT INTO  USERS (USERNAME, PASSWORD, ENABLED) VALUES ('test1', 'password123', true);
INSERT INTO  AUTHORITIES (USERNAME, AUTHORITY) VALUES ('test1', 'ROLE_USER');

INSERT INTO  USERS (USERNAME, PASSWORD, ENABLED) VALUES  ('test2', 'password123', true);
INSERT INTO  AUTHORITIES (USERNAME, AUTHORITY) VALUES ('test2', 'ROLE_USER');

INSERT INTO  USERS (USERNAME, PASSWORD, ENABLED) VALUES ('test3', 'password123', true);
INSERT INTO  AUTHORITIES (USERNAME, AUTHORITY) VALUES ('test3', 'ROLE_ADMIN');